version: '3'

services:
  db:
    image: postgres:latest
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=postgres
    - POSTGRES_INITDB_ARGS=--auth-host=md5
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - postgres:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      args:
        ENVIRONMENT: dev
    environment:
    - DJANGO_MANAGEPY_COLLECTSTATIC=off
    volumes:
    - ./src:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
    - "80:80"
    command:
    - python
    - manage.py
    - runserver
    - 0.0.0.0:80

volumes:
  postgres: